### ISSUE TITLE
Old version of sentence-camembert-base evaluated in F-MTEB?

### ISSUE THREAD

**Issue by tlevyaleia** [Lyon-NLP/mteb-french#64]
Hello,
The French MTEB leaderboard is really a great work.
I wonder why you evaluated the "dangvantuan/sentence-camembert-large" model whereas a more recent version exists here:
https://huggingface.co/Lajavaness/sentence-camembert-large
The latter version is claimed to have slightly better performance. Would be good to add it to the benchmark.
I would be happy to help/contribute to this if needed.
THanks

**Comment by imenelydiaker** [comment]
Hello @tlevyaleia,

Thank you for highlithing this, we'll add this version to our new experiments, results should come soon!

**Comment by tlevyaleia** [comment]
Great. Thanks for your feedback. 
I will follow the new results with interest.
Thomas
